### ISSUE TITLE
"X11 clipboard error : Selection timed out" on cargo test

### ISSUE THREAD

**Issue by gustawdaniel** [Canop/terminal-clipboard#6]
I am happy user of this library and it works in my project, but I wanted to help and update deplendencies.

after `cargo test` I have seen this

```
➜ cargo test 
   Compiling terminal-clipboard v0.3.1 (/home/daniel/exp/terminal-clipboard)
    Finished test [unoptimized + debuginfo] target(s) in 0.33s
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running unittests src/lib.rs (target/debug/deps/terminal_clipboard-fff70f11c1e6b922)

running 2 tests
test local::test_local_clipboard ... ok
test clipboard_tests::write_read ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

   Doc-tests terminal-clipboard

running 2 tests
test src/lib.rs - (line 10) ... FAILED
test src/lib.rs - (line 42) ... FAILED

failures:

---- src/lib.rs - (line 10) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClipboardError { message: "X11 clipboard error : Selection timed out" }', src/lib.rs:5:53
stack backtrace:
   0:     0x564c6f954c2a - std::backtrace_rs::backtrace::libunwind::trace::hb525d69e070ade81
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564c6f954c2a - std::backtrace_rs::backtrace::trace_unsynchronized::hc013ba6c022c8cc0
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564c6f954c2a - std::sys_common::backtrace::_print_fmt::hc99069d428720acc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564c6f954c2a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b2dfd5fb54878e3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564c6f96fcee - core::fmt::write::he277a08b33a83db8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/fmt/mod.rs:1232:17
   5:     0x564c6f952bc5 - std::io::Write::write_fmt::h6a5aa3320aae0280
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/io/mod.rs:1684:15
   6:     0x564c6f9549f5 - std::sys_common::backtrace::_print::h763b5adb4e9083ff
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x564c6f9549f5 - std::sys_common::backtrace::print::h5a4028b32a3df8a2
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x564c6f9561af - std::panicking::default_hook::{{closure}}::h0c8c81b9641f8819
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:271:22
   9:     0x564c6f955eeb - std::panicking::default_hook::h5bf7cd33f355743b
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:290:9
  10:     0x564c6f956758 - std::panicking::rust_panic_with_hook::h11aed2986f5c5154
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:692:13
  11:     0x564c6f956659 - std::panicking::begin_panic_handler::{{closure}}::h5030a267c334a760
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:583:13
  12:     0x564c6f955096 - std::sys_common::backtrace::__rust_end_short_backtrace::hf19b9029d2a05570
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x564c6f956362 - rust_begin_unwind
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:579:5
  14:     0x564c6f900273 - core::panicking::panic_fmt::hc179041817e007c3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:64:14
  15:     0x564c6f900663 - core::result::unwrap_failed::h6bf7eafb294b41fd
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/result.rs:1750:5
  16:     0x564c6f900c94 - core::result::Result<T,E>::unwrap::h9b5724d341562b27
  17:     0x564c6f900e61 - rust_out::main::_doctest_main_src_lib_rs_10_0::h4dec3299d9943463
  18:     0x564c6f900df6 - rust_out::main::h99b239c25a2c2a8c
  19:     0x564c6f900ae3 - core::ops::function::FnOnce::call_once::hd0939d8a94297542
  20:     0x564c6f900a69 - std::sys_common::backtrace::__rust_begin_short_backtrace::h291a8f7cd3670362
  21:     0x564c6f900ab9 - std::rt::lang_start::{{closure}}::hdd250720ab05629f
  22:     0x564c6f9509bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h87ce1ff925f3f399
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:287:13
  23:     0x564c6f9509bc - std::panicking::try::do_call::hc4f2b80657aeb718
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  24:     0x564c6f9509bc - std::panicking::try::h3c47de03d3ebd300
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  25:     0x564c6f9509bc - std::panic::catch_unwind::h61c54a435b77e782
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  26:     0x564c6f9509bc - std::rt::lang_start_internal::{{closure}}::hede90a79f254ba78
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:48
  27:     0x564c6f9509bc - std::panicking::try::do_call::hb36647b8be9e600f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  28:     0x564c6f9509bc - std::panicking::try::hfad0ec6acceedd9e
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  29:     0x564c6f9509bc - std::panic::catch_unwind::h9589894eaedfd8e8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  30:     0x564c6f9509bc - std::rt::lang_start_internal::h040b0a6c56929afc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:20
  31:     0x564c6f900a97 - std::rt::lang_start::h8e8d01aee0fbf192
  32:     0x564c6f900f45 - main
  33:     0x7f3d65673510 - __libc_start_call_main
  34:     0x7f3d656735c9 - __libc_start_main@GLIBC_2.2.5
  35:     0x564c6f900845 - _start
  36:                0x0 - <unknown>


---- src/lib.rs - (line 42) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClipboardError { message: "X11 clipboard error : Selection timed out" }', src/lib.rs:6:53
stack backtrace:
   0:     0x564cd5fd5c2a - std::backtrace_rs::backtrace::libunwind::trace::hb525d69e070ade81
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564cd5fd5c2a - std::backtrace_rs::backtrace::trace_unsynchronized::hc013ba6c022c8cc0
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564cd5fd5c2a - std::sys_common::backtrace::_print_fmt::hc99069d428720acc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564cd5fd5c2a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b2dfd5fb54878e3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564cd5ff0cee - core::fmt::write::he277a08b33a83db8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/fmt/mod.rs:1232:17
   5:     0x564cd5fd3bc5 - std::io::Write::write_fmt::h6a5aa3320aae0280
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/io/mod.rs:1684:15
   6:     0x564cd5fd59f5 - std::sys_common::backtrace::_print::h763b5adb4e9083ff
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x564cd5fd59f5 - std::sys_common::backtrace::print::h5a4028b32a3df8a2
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x564cd5fd71af - std::panicking::default_hook::{{closure}}::h0c8c81b9641f8819
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:271:22
   9:     0x564cd5fd6eeb - std::panicking::default_hook::h5bf7cd33f355743b
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:290:9
  10:     0x564cd5fd7758 - std::panicking::rust_panic_with_hook::h11aed2986f5c5154
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:692:13
  11:     0x564cd5fd7659 - std::panicking::begin_panic_handler::{{closure}}::h5030a267c334a760
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:583:13
  12:     0x564cd5fd6096 - std::sys_common::backtrace::__rust_end_short_backtrace::hf19b9029d2a05570
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x564cd5fd7362 - rust_begin_unwind
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:579:5
  14:     0x564cd5f81273 - core::panicking::panic_fmt::hc179041817e007c3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:64:14
  15:     0x564cd5f81663 - core::result::unwrap_failed::h6bf7eafb294b41fd
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/result.rs:1750:5
  16:     0x564cd5f81c94 - core::result::Result<T,E>::unwrap::h9b5724d341562b27
  17:     0x564cd5f81e61 - rust_out::main::_doctest_main_src_lib_rs_42_0::h277eb509f7ffdc1a
  18:     0x564cd5f81df6 - rust_out::main::h99b239c25a2c2a8c
  19:     0x564cd5f81ae3 - core::ops::function::FnOnce::call_once::hd0939d8a94297542
  20:     0x564cd5f81a69 - std::sys_common::backtrace::__rust_begin_short_backtrace::h291a8f7cd3670362
  21:     0x564cd5f81ab9 - std::rt::lang_start::{{closure}}::hdd250720ab05629f
  22:     0x564cd5fd19bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h87ce1ff925f3f399
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:287:13
  23:     0x564cd5fd19bc - std::panicking::try::do_call::hc4f2b80657aeb718
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  24:     0x564cd5fd19bc - std::panicking::try::h3c47de03d3ebd300
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  25:     0x564cd5fd19bc - std::panic::catch_unwind::h61c54a435b77e782
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  26:     0x564cd5fd19bc - std::rt::lang_start_internal::{{closure}}::hede90a79f254ba78
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:48
  27:     0x564cd5fd19bc - std::panicking::try::do_call::hb36647b8be9e600f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  28:     0x564cd5fd19bc - std::panicking::try::hfad0ec6acceedd9e
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  29:     0x564cd5fd19bc - std::panic::catch_unwind::h9589894eaedfd8e8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  30:     0x564cd5fd19bc - std::rt::lang_start_internal::h040b0a6c56929afc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:20
  31:     0x564cd5f81a97 - std::rt::lang_start::h8e8d01aee0fbf192
  32:     0x564cd5f81f45 - main
  33:     0x7ff170cb9510 - __libc_start_call_main
  34:     0x7ff170cb95c9 - __libc_start_main@GLIBC_2.2.5
  35:     0x564cd5f81845 - _start
  36:                0x0 - <unknown>



failures:
    src/lib.rs - (line 10)
    src/lib.rs - (line 42)

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.29s

error: doctest failed, to rerun pass `--doc`

terminal-clipboard on  master [?] is 📦 0.3.1 via 🦀 1.70.0 took 2,9s …
➜ 

terminal-clipboard on  master [?] is 📦 0.3.1 via 🦀 1.70.0 …
➜ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running unittests src/lib.rs (target/debug/deps/terminal_clipboard-fff70f11c1e6b922)

running 2 tests
test local::test_local_clipboard ... ok
test clipboard_tests::write_read ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

   Doc-tests terminal-clipboard

running 2 tests
test src/lib.rs - (line 42) ... FAILED
test src/lib.rs - (line 10) ... FAILED

failures:

---- src/lib.rs - (line 42) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClipboardError { message: "X11 clipboard error : Selection timed out" }', src/lib.rs:6:53
stack backtrace:
   0:     0x562ce8150c2a - std::backtrace_rs::backtrace::libunwind::trace::hb525d69e070ade81
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562ce8150c2a - std::backtrace_rs::backtrace::trace_unsynchronized::hc013ba6c022c8cc0
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562ce8150c2a - std::sys_common::backtrace::_print_fmt::hc99069d428720acc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562ce8150c2a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b2dfd5fb54878e3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562ce816bcee - core::fmt::write::he277a08b33a83db8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/fmt/mod.rs:1232:17
   5:     0x562ce814ebc5 - std::io::Write::write_fmt::h6a5aa3320aae0280
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/io/mod.rs:1684:15
   6:     0x562ce81509f5 - std::sys_common::backtrace::_print::h763b5adb4e9083ff
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x562ce81509f5 - std::sys_common::backtrace::print::h5a4028b32a3df8a2
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x562ce81521af - std::panicking::default_hook::{{closure}}::h0c8c81b9641f8819
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:271:22
   9:     0x562ce8151eeb - std::panicking::default_hook::h5bf7cd33f355743b
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:290:9
  10:     0x562ce8152758 - std::panicking::rust_panic_with_hook::h11aed2986f5c5154
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:692:13
  11:     0x562ce8152659 - std::panicking::begin_panic_handler::{{closure}}::h5030a267c334a760
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:583:13
  12:     0x562ce8151096 - std::sys_common::backtrace::__rust_end_short_backtrace::hf19b9029d2a05570
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x562ce8152362 - rust_begin_unwind
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:579:5
  14:     0x562ce80fc273 - core::panicking::panic_fmt::hc179041817e007c3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:64:14
  15:     0x562ce80fc663 - core::result::unwrap_failed::h6bf7eafb294b41fd
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/result.rs:1750:5
  16:     0x562ce80fcc94 - core::result::Result<T,E>::unwrap::h9b5724d341562b27
  17:     0x562ce80fce61 - rust_out::main::_doctest_main_src_lib_rs_42_0::h277eb509f7ffdc1a
  18:     0x562ce80fcdf6 - rust_out::main::h99b239c25a2c2a8c
  19:     0x562ce80fcae3 - core::ops::function::FnOnce::call_once::hd0939d8a94297542
  20:     0x562ce80fca69 - std::sys_common::backtrace::__rust_begin_short_backtrace::h291a8f7cd3670362
  21:     0x562ce80fcab9 - std::rt::lang_start::{{closure}}::hdd250720ab05629f
  22:     0x562ce814c9bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h87ce1ff925f3f399
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:287:13
  23:     0x562ce814c9bc - std::panicking::try::do_call::hc4f2b80657aeb718
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  24:     0x562ce814c9bc - std::panicking::try::h3c47de03d3ebd300
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  25:     0x562ce814c9bc - std::panic::catch_unwind::h61c54a435b77e782
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  26:     0x562ce814c9bc - std::rt::lang_start_internal::{{closure}}::hede90a79f254ba78
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:48
  27:     0x562ce814c9bc - std::panicking::try::do_call::hb36647b8be9e600f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  28:     0x562ce814c9bc - std::panicking::try::hfad0ec6acceedd9e
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  29:     0x562ce814c9bc - std::panic::catch_unwind::h9589894eaedfd8e8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  30:     0x562ce814c9bc - std::rt::lang_start_internal::h040b0a6c56929afc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:20
  31:     0x562ce80fca97 - std::rt::lang_start::h8e8d01aee0fbf192
  32:     0x562ce80fcf45 - main
  33:     0x7f280e8b3510 - __libc_start_call_main
  34:     0x7f280e8b35c9 - __libc_start_main@GLIBC_2.2.5
  35:     0x562ce80fc845 - _start
  36:                0x0 - <unknown>


---- src/lib.rs - (line 10) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClipboardError { message: "X11 clipboard error : Selection timed out" }', src/lib.rs:5:53
stack backtrace:
   0:     0x55b122b96c2a - std::backtrace_rs::backtrace::libunwind::trace::hb525d69e070ade81
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b122b96c2a - std::backtrace_rs::backtrace::trace_unsynchronized::hc013ba6c022c8cc0
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b122b96c2a - std::sys_common::backtrace::_print_fmt::hc99069d428720acc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55b122b96c2a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b2dfd5fb54878e3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b122bb1cee - core::fmt::write::he277a08b33a83db8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/fmt/mod.rs:1232:17
   5:     0x55b122b94bc5 - std::io::Write::write_fmt::h6a5aa3320aae0280
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/io/mod.rs:1684:15
   6:     0x55b122b969f5 - std::sys_common::backtrace::_print::h763b5adb4e9083ff
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55b122b969f5 - std::sys_common::backtrace::print::h5a4028b32a3df8a2
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55b122b981af - std::panicking::default_hook::{{closure}}::h0c8c81b9641f8819
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:271:22
   9:     0x55b122b97eeb - std::panicking::default_hook::h5bf7cd33f355743b
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:290:9
  10:     0x55b122b98758 - std::panicking::rust_panic_with_hook::h11aed2986f5c5154
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:692:13
  11:     0x55b122b98659 - std::panicking::begin_panic_handler::{{closure}}::h5030a267c334a760
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:583:13
  12:     0x55b122b97096 - std::sys_common::backtrace::__rust_end_short_backtrace::hf19b9029d2a05570
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55b122b98362 - rust_begin_unwind
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:579:5
  14:     0x55b122b42273 - core::panicking::panic_fmt::hc179041817e007c3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:64:14
  15:     0x55b122b42663 - core::result::unwrap_failed::h6bf7eafb294b41fd
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/result.rs:1750:5
  16:     0x55b122b42c94 - core::result::Result<T,E>::unwrap::h9b5724d341562b27
  17:     0x55b122b42e61 - rust_out::main::_doctest_main_src_lib_rs_10_0::h4dec3299d9943463
  18:     0x55b122b42df6 - rust_out::main::h99b239c25a2c2a8c
  19:     0x55b122b42ae3 - core::ops::function::FnOnce::call_once::hd0939d8a94297542
  20:     0x55b122b42a69 - std::sys_common::backtrace::__rust_begin_short_backtrace::h291a8f7cd3670362
  21:     0x55b122b42ab9 - std::rt::lang_start::{{closure}}::hdd250720ab05629f
  22:     0x55b122b929bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h87ce1ff925f3f399
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:287:13
  23:     0x55b122b929bc - std::panicking::try::do_call::hc4f2b80657aeb718
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  24:     0x55b122b929bc - std::panicking::try::h3c47de03d3ebd300
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  25:     0x55b122b929bc - std::panic::catch_unwind::h61c54a435b77e782
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  26:     0x55b122b929bc - std::rt::lang_start_internal::{{closure}}::hede90a79f254ba78
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:48
  27:     0x55b122b929bc - std::panicking::try::do_call::hb36647b8be9e600f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  28:     0x55b122b929bc - std::panicking::try::hfad0ec6acceedd9e
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  29:     0x55b122b929bc - std::panic::catch_unwind::h9589894eaedfd8e8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  30:     0x55b122b929bc - std::rt::lang_start_internal::h040b0a6c56929afc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/rt.rs:148:20
  31:     0x55b122b42a97 - std::rt::lang_start::h8e8d01aee0fbf192
  32:     0x55b122b42f45 - main
  33:     0x7f9897189510 - __libc_start_call_main
  34:     0x7f98971895c9 - __libc_start_main@GLIBC_2.2.5
  35:     0x55b122b42845 - _start
  36:                0x0 - <unknown>



failures:
    src/lib.rs - (line 10)
    src/lib.rs - (line 42)

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.27s

error: doctest failed, to rerun pass `--doc`
```

**Comment by gustawdaniel** [comment]
Fixed by replacing `/*!` by `/*` in first line of `src/lib.rs`
